production:
  :adapter: mysql2
  :encoding: utf8
  :database: jdash_production
  :pool: 5
  :username: root
  :password: root123

testing:
  :adapter: mysql2
  :encoding: utf8
  :database: jdash_testing
  :pool: 5
  :username: root
  :password: root123

development:
  :adapter: mysql2
  :encoding: utf8
  :database: jdash_development
  :pool: 5
  :username: root
  :password: root123
  :socket: /tmp/mysql.sock
