development:
  adapter:mysql2
  encoding: utf8
  database:jdash_development
  pool5
  username: root
  password: root123
  socket: /tmp/mysql.sock


testing:
  adapter:mysql2
  encoding: utf8
  database:jdash_testing
  pool5
  username: root
  password: root123
  socket: /tmp/mysql.sock

production:
  adapter:mysql2
  encoding: utf8
  database:jdash_production
  pool5
  username: root
  password: root123
  socket: /tmp/mysql.sock
